id = "http"
name = "http"
description = "Highlights .http files"
version = "0.0.3"
schema_version = 1
authors = ["tylerhanson921@gmail.com"]
repository = "https://github.com/tie304/zed-http"


[grammars.http]
repository = "https://github.com/ToyVoDev/tree-sitter-http"
commit = "07612be7657611df0ddbefaff0e1f48f6cfd006c"
